Repository openscilab/tocount, pull requests merged in 2025-08, with the labels that each got.

#3 Include a table to report the performance metrics for each model. Closes #2
  README.md
Labels: documentation

#5 Add test structure and CI workflow
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  tests/test_rule_based.py
Labels: test

#8 Text Estimator
  README.md
  tests/test_rule_based.py
  tocount/functions.py
Labels: documentation, enhancement

#9 Version 0.1
  CHANGELOG.md
  README.md
  otherfiles/meta.yaml
  setup.py
Labels: release
