Repository openscilab/tocount, pull requests merged in 2025-10, with the labels that each got.

#15 Version 0.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
  tocount/params.py
Labels: release

#17 Add cl100k model
  README.md
  tocount/functions.py
  tocount/params.py
  tocount/tiktoken_cl100k/__init__.py
  tocount/tiktoken_cl100k/functions.py
  tocount/tiktoken_r50k/__init__.py
  tocount/tiktoken_r50k/functions.py
Labels: enhancement

#18 add scalers
  tocount/params.py
  tocount/tiktoken_cl100k/functions.py
  tocount/tiktoken_r50k/functions.py
Labels: documentation, enhancement
